volumes:
  dbdata:

services:
  postgres:
    image: postgres:16
    ports:
      - "${PORT:-5432}:5432"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    restart: always
